build:
  image: go1.6
  commands:
    - go get github.com/codegangsta/cli
    - go get github.com/google/go-github/github
    - make
  notify:
    email:
      recipients:
        - zpeters@gmail.com
