language: go
sudo: true
go:
  - 1.6
script:
  - go test -v ./...
before_install:
  - sudo add-apt-repository ppa:masterminds/glide
  - sudo apt-get update
  - sudo apt-get install glide
install:
  - glide up
notifications:
  email:
    recipients:
      - zpeters@gmail.com
    on_failure: always
    on_success: always
