language: go
sudo: false
notifications:
   email:
      recipients:
         - zpeters@gmail.com
      on_success: always
      on_failure: always

script:
   - go get "github.com/codegangsta/cli"
   - go get "github.com/google/go-github/github"
   - make
