language: go
sudo: false
go:
  - 1.6
script:
  - go test -v ./...
before_install:
  - add-apt-repository ppa:masterminds/glide
  - apt-get update
  - apt-get install glide
install:
  - glide up
notifications:
  email:
    recipients:
      - zpeters@gmail.com
    on_failure: always
    on_success: always
