language: go
sudo: false
go:
  - 1.6
install:
  - git submodule init
  - git submodule update
script:
  - make
notifications:
  email:
    recipients:
      - zpeters@gmail.com
    on_failure: always
    on_success: always
