language: go
sudo: false
go:
  - 1.6
install:
  - go get "github.com/codegangsta/cli"
  - go get "github.com/google/go-github/github"
script:
  - go build
notifications:
  email:
    recipients:
      - zpeters@gmail.com
    on_failure: always
    on_success: always
